### ISSUE TITLE
Where to find documentation? 

### ISSUE THREAD

**Issue by rsheasby** [adolya/Nlog.RabbitMQ#12]
Hi.

Just wanted to find out where the documentation for this package is? There's no information on the Readme and the wiki isn't accessible(It just keeps redirecting to the code tab when clicked).

**Comment by marrrschine** [comment]
I would also appreciate some info on this.

**Comment by adolya** [comment]
There is an example project.

**Comment by adolya** [comment]
Let me know if its not enough

**Comment by rsheasby** [comment]
Yeah I think a bit more would be a lot better. It's not easy to figure out what the options in the config are and such just by example. You really need both, especially given that this project is directly referenced by NLog and as such is not merely a hobbyist "for fun" project, but is actually a project some people may hope to use in professional contexts(as I did and ended up turning to Serilog instead). It's not that the example is bad, but that it's much easier to process a reference documentation when trying to remember what a parameter does or something like that.

**Comment by snakefoot** [comment]
#13 Have improved Readme.md with more examples.

**Comment by adolya** [comment]
They are both merged

**Comment by snakefoot** [comment]
Yes but this issue was raised before the PRs was merged. Maybe this issue can be closed, unless something is missing?


Sent from my Sony Xperia


---- Artem wrote ----


They are both merged

**Comment by adolya** [comment]
So can we close it? 
Builds are automated now, it will be easier to publish packages.
