### ISSUE TITLE
Target NLog 4.5

### ISSUE THREAD

**Issue by wonea** [adolya/Nlog.RabbitMQ#2]
NLog 5 has been discontinued, we need to target NLog 4.5

https://twitter.com/NLogOfficial

**Comment by wonea** [comment]
Merged #3

**Comment by JoostvdB94** [comment]
Since this change, I can no longer find the ` Nlog.RabbitMQ.Target.RabbitMQTarget`. I could however find the class when using 2.4.0 (With NLog 5)
