### ISSUE TITLE
New NuGet package release

### ISSUE THREAD

**Issue by wonea** [adolya/Nlog.RabbitMQ#9]
Hello, can we have a new NuGet release please? For the new changes which have just been added.

**Comment by adolya** [comment]
https://www.nuget.org/packages/Nlog.RabbitMQ.Target/2.5.1

**Comment by wonea** [comment]
Sorry the package is not right. The different frameworks should be targetted in different folders.

![image](https://user-images.githubusercontent.com/557192/38681342-51de3ba2-3e60-11e8-826d-c12c50edcfd5.png)

It should look like this

![image](https://user-images.githubusercontent.com/557192/38681517-cb4d6fe4-3e60-11e8-8ef6-4d7b06a00676.png)

Let Visual Studio build the NuGet file, and it will sort out the frameworks. All you need to do is increment the package version.

![image](https://user-images.githubusercontent.com/557192/38681605-fd33e07e-3e60-11e8-88d2-acaebf1d915c.png)

I've created a pull request to help

**Comment by wonea** [comment]
What does NuGet say is wrong with the package?

**Comment by wonea** [comment]
Can we bump the Newtonsoft package version to the latest version 11.0.2? Sorry using version 10 causes problems for me downstream.

**Comment by wonea** [comment]
Okay, that is a little odd. Perhaps just keep with manually building the package. Could you commit the nupkg file in, so I can make some changes?

**Comment by snakefoot** [comment]
Looks like it is manual build that is broken. The build created by dotnet pack is correct, but rejected by nuget for some reason



Sent from my Samsung device


-------- Original message --------

**Comment by adolya** [comment]
I pushed the nuspec. Please check

**Comment by adolya** [comment]
The title of your package, 'Nlog.Targets.RabbitMQ', is similar to the ID of an existing package, which can cause confusion with our users. Please modify the title of your package and try uploading again.

**Comment by snakefoot** [comment]
Should fix the product and title in csproj to NLog.RabbitMQ.Targets (instead of Nlog.Targets.RabbitMQ)



Sent from my Samsung device


-------- Original message --------

**Comment by wonea** [comment]
Thanks!

**Comment by snakefoot** [comment]
Updated PR #11 to include fix of csproj product and title. Please merge and release.

**Comment by snakefoot** [comment]
@adolya Polite poke. Any chance the above PR can be merged to see if the nuget-problem is fixed?

**Comment by snakefoot** [comment]
@adolya Are there still issues with publishing to nuget after having applied the last PR ?

**Comment by snakefoot** [comment]
@adolya Another polite poke. Any chance you can build a nuget-package on the updated code:

`dotnet pack src\Nlog.RabbitMQ.Target --configuration Release --include-symbols`

**Comment by adolya** [comment]
I finally solved issue with Nuget, it was actually with my account.
I deleted nuspec, and verified that dotnet pack works, actually last package.
Version 2.6.22. That actually contains upgrade to .NET 4.7 is available

**Comment by snakefoot** [comment]
@adolya Glad you resolved the issue with the nuget-package. Have created  #13 that allows use of net451, since no need to force upgrade.

**Comment by adolya** [comment]
I was finally able to pack  and push the project with command line
Please download the latest version

**Comment by snakefoot** [comment]
@adolya Thank for the update. Have created #19 with some more enhancements.
